# Generated by Django 4.2 on 2025-03-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('mobile_no', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=254)),
                ('education', models.CharField(max_length=100)),
                ('year_passout', models.CharField(max_length=10)),
                ('required_course', models.CharField(max_length=100)),
                ('placement', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('profession', models.CharField(choices=[('IT', 'IT'), ('NON-IT', 'Non-IT')], max_length=10)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('pf', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('uan_no', models.CharField(blank=True, max_length=20, null=True)),
                ('form_16', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField()),
                ('pan_aadhar', models.CharField(blank=True, max_length=20, null=True)),
                ('refer_by', models.CharField(blank=True, max_length=100, null=True)),
                ('referer_mbl', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
