# Generated by Django 4.1.13 on 2025-03-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('round', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('student_mobile', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
